version: '3.8'

services:
  qaoa-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: qaoa-portfolio-optimizer-prod
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - WORKERS=4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qaoa-prod-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: qaoa-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Optional: for SSL certificates
    depends_on:
      - qaoa-api
    restart: unless-stopped
    networks:
      - qaoa-prod-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  qaoa-prod-network:
    driver: bridge