version: '3.8'

services:
  qaoa-api:
    build: .
    container_name: qaoa-portfolio-optimizer
    ports:
      - "9000:9000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qaoa-network

networks:
  qaoa-network:
    driver: bridge